### ISSUE TITLE
Robot Speed

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#1]
Code is looking great!

However, I noticed that the speeds in the TankDrive.java file are unregulated. Try adding a variable in RobotMap that contains the desired drivetrain speed and then scale down the values sent in to the tankDrive function. This makes the drivetrain a bit easier to control since it might be too fast initially.

**Comment by ayushdewan** [comment]
This is also a good way to start getting used to raising issues, making commits to resolve issues, and using GitHub to communicate.

**Comment by aditya917** [comment]
I just fixed the speed regulation in the code. If you go to the Tankdrive.java file, you can see that I added a multiplier of 0.5. This allows the robot to maintain a medium speed which is perfect for testing purposes.

**Comment by ayushdewan** [comment]
Two Recommendations:
- Add a variable that contains the coefficient so you only have to change it in one place
- Use more descriptive commit titles
