### ISSUE TITLE
Iterative or Command Based Code Repository

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#10]
Let's have a quick vote for what we should do this year. React to this issue with a rocket for iterative and a heart for command based. Feel free to add any reasons why you want on or the other.

**Comment by aditya917** [comment]
I am fine with anything, however, I feel like the command based template is a bit more organized for me.

**Comment by ayushdewan** [comment]
I converted the master branch to iterative code and deleted the 'iterative' branch. If you want to access the command based code, you can go back down the commit history.

**Comment by ayushdewan** [comment]
In case you were wondering, you could find the command based files here:
https://github.com/Team2489/Generic-Robot-Code/tree/c42d2d7b72dba9b843c6edd8d8c690fa270c7f22/src/main/java/frc/robot
