### ISSUE TITLE
Remove DifferentialDrive and SpeedControllerGroup

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#2]
To do this you have to change WPI_TalonSRX to TalonSRX. Consult the phoenix documentation for how to drive the motors at certain powers. Make sure to drive both of the motors on the left side at the same power and both of the motors on the right side the same way. This makes it easier to inject closed-loop control in the teleop loop.

**Comment by aditya917** [comment]
I think you are talking about slaves and masters. There is a command which allows you to make the slaves do the same tasks as the masters.
Ex(in my code): 
slaves- rightBackMotor, leftBackMotor
masters-rightFrontMotor, leftFrontMotor
In the case that you are referring to this, I would gladly change it!

**Comment by ayushdewan** [comment]
Yes! I am referring to exactly that. The way I did it was to set the "slave" motors as followers to their respective masters. 

`   rightBackMotor.set(ControlMode.Follower, RobotMap.RIGHT_FRONT_MOTOR);
     leftBackMotor.set(ControlMode.Follower, RobotMap.LEFT_FRONT_MOTOR);`

**Comment by aditya917** [comment]
In order to complete this task, wouldn't you need a differential drive variable?

**Comment by avyayv** [comment]
No, you should be able to just run something like `master.set(ControlMode.PercentOutput, speed)` for each of the masters

**Comment by aditya917** [comment]
I understood that part, but don't you need a differential drive variable in order for the joysticks to control the motors?

**Comment by aditya917** [comment]
I still don't understand. Don't you need a differential drive variable to make the joysticks control the motors?

**Comment by ayushdewan** [comment]
You don't need differential drive since you are controlling each motor separately. 

`leftFrontMotor.set(ControlMode.PercentOutput, leftSpeed);
rightFrontMotor.set(ControlMode.PercentOutput, rightSpeed);`

leftSpeed and rightSpeed both hold the joystick data.

**Comment by avyayv** [comment]
Since the DriveTrain class has the method tankDrive, all you should have to do is just call the tankDrive method in the TankDrive command file. The joystick output goes directly into the method, so there's no need for diff. drive.

**Comment by aditya917** [comment]
I realized I could approach the problem in a much simpler way. If the joystick values are considered as the speed of the robot, I just added them to the speed of the masters. I also realized that there is no need for the tank drive command so I deleted it. This is how the code looks now.
`rightFrontMaster.set(ControlMode.PercentOutput,Robot.oi.rightJoystick.getY()*RobotMap.SPEED_MULTIPLIER);
  leftFrontMaster.set(ControlMode.PercentOutput,Robot.oi.leftJoystick.getY()*RobotMap.SPEED_MULTIPLIER);`

**Comment by aditya917** [comment]
I know the code looks messy but it looks like it could work well and is not too hard to read!

**Comment by ayushdewan** [comment]
Yeah, that's the way.

**Comment by aditya917** [comment]
Just to make sure, the command is not necessary right? 
P.S. I already deleted the Tank Drive file.

**Comment by avyayv** [comment]
If you plan on keeping the master branch as command-based (I suggest that we do, since we have an iterative branch), you need the TankDrive command. 
Further, I highly suggest that you keep the `tankDrive` method in the Drivetrain class, as it makes your code far more modular.

**Comment by aditya917** [comment]
Well, to be honest, we don't need a command anymore since everything since we added the slaves and masters. We also don't need the tankDrive method because the Drivetrain method has the same functionality. I just used the Command-Based Framework as it gives me more templates to work with.

**Comment by avyayv** [comment]
Yeah, I understand. However, I would really prefer it if you kept the master branch completely command-based. If you look at the branches, you will see an iterative branch which is written completely in iterative code. 

What I would suggest for you to do to maximize the utility of this repo is to revert to your last commit and just alter your code in the drivetrain class.

@aditya917 To get a better understanding about how it works, you should look at @ayushdewan's branch in iterative, but maintain the command-based structure.

**Comment by ayushdewan** [comment]
@aditya917 doesn't have to revert back to any commits actually. Only one line of code is needed: add back the tankDrive method signature and it should be back to a working state.

**Comment by aditya917** [comment]
How do I do that?

**Comment by ayushdewan** [comment]
Where it says public Drivetrain(), change that to public void tankDrive()

thats it

**Comment by ayushdewan** [comment]
Add back the commands directory along with the tank drive command. In the TankDrive.java command file, add in the new drive code.

**Comment by avyayv** [comment]
I just thought it would be easier to revert to his last commit to get back the commands that he deleted with his most recent commit.

**Comment by ayushdewan** [comment]
@michaelkamensky could you please offer some help as well since we are dealing with command-based code.

**Comment by aditya917** [comment]
I am running into problems now as I am dealing with unmerged files.

**Comment by ayushdewan** [comment]
@avyayv Yeah, I just noticed that. Reverting to the commit before is a solution.

**Comment by ayushdewan** [comment]
@aditya917 Follow these instructions:
- Delete this repository from your computer 
- Run a `git clone` for this repo and you'll get back a working copy
- Fix the code from there

**Comment by aditya917** [comment]
I just fixed the error.

**Comment by ayushdewan** [comment]
Almost there. Just two more things:
- put the follow function calls for the slave motors inside a constructor for the drivetrain class since they only need to be run once
- put the drive function calls inside the TankDrive command file since it's currently empty

**Comment by aditya917** [comment]
What do you mean by the drive function?

**Comment by avyayv** [comment]
The function(`tankDrive`) that you create in the Drivetrain class needs to be called in the TankDrive command

**Comment by aditya917** [comment]
I understand what you are saying but I am unfamiliar with the syntax. Could you help me out?
I have been looking through a countless number of articles but none seem to help.

**Comment by ayushdewan** [comment]
Copy paste the contents of the tankDrive method in Drivetrain.java to the execute method in TankDrive.java.

**Comment by aditya917** [comment]
I fixed the issue. You can check it out on the Drivetrain subsystem file and Tankdrive command file.

**Comment by ayushdewan** [comment]
Before committing, remember to check if your code passes the build test (right click build.gradle and select build robot code) and try your best to indent code between {}. Otherwise, I fixed the problems. Please check the latest commit. Happy new year.
