### ISSUE TITLE
Motor Polarity Change

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#4]
Since this is for tank drive code, one of the sides needs to be inverted depending on what we define as the front/back of the chassis.

**Comment by aditya917** [comment]
Right! I was previously thinking about this error but I forgot to change it. Normally, I would expect the left side of the robots to reversed or its values need to be changed to negatives.

**Comment by ayushdewan** [comment]
Yup. Just add in a negative sign somewhere and its fixed. But we would need to make this change later on since the front/back of the robot may change due to the design.

**Comment by aditya917** [comment]
I added the negatives under the commit: Reversed Polarity for left motors.

**Comment by ayushdewan** [comment]
whoops its supposed to be for the right motor :(

**Comment by aditya917** [comment]
Oh, don't worry. But how do you know?

**Comment by ayushdewan** [comment]
Positive polarity to a CIM motor means it spins clockwise. So for the left side it would be correct but the right side would need to be inverted. I could show you on Saturday at kickoff it's easier to explain with a diagram.

**Comment by aditya917** [comment]
Ah, right! Yes, I completely understand what you are saying!
