### ISSUE TITLE
NEODrivetrain Class

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#5]
Could we also add another subsystem class for a drivetrain that has NEO motors. Then we just need to change all instances of "Drivetrain" in Robot.java to "NEODrivetrain".

**Comment by aditya917** [comment]
Sure, do we make another subsystem or just build on what we have now?

**Comment by ayushdewan** [comment]
Just another subsystem would be best.

**Comment by aditya917** [comment]
Great I just need to import the libraries.

**Comment by aditya917** [comment]
The neo motors use the spark max libraries, right?

**Comment by ayushdewan** [comment]
yea

**Comment by ayushdewan** [comment]
Real quickly could you also remove the negative sign from this line of code in Drivetrain.java
``` java
rightBackSlave.set(ControlMode.Follower, -RobotMap.RIGHT_FRONT_MASTER);
```

The input to this function is the ID to the talon.

**Comment by aditya917** [comment]
Sorry wrong place!

**Comment by ayushdewan** [comment]
The line doesn't need the negative sign at all. You already included it in the drive function. Just remove it entirely. The rightBackSlave.set method is a void method.

**Comment by aditya917** [comment]
I'm not sure what line you are talking about.

**Comment by ayushdewan** [comment]
``` java
-rightBackSlave.set(ControlMode.Follower, RobotMap.RIGHT_FRONT_MASTER);
```

in Drivetrain.java

**Comment by aditya917** [comment]
Right, I'm sorry about that. I didn't realize that I was dealing with slaves and masters. Also, I installed the Rev Robotics library so I should be done with the subsystem soon.

**Comment by ayushdewan** [comment]
Thanks for the fix.

**Comment by aditya917** [comment]
I completed the NEODrivetrain subsystem and NEOTankDrive command. 
**Note**:

- the right master is inverted so I didn't add the negative sign on the command.

**Comment by ayushdewan** [comment]
You actually need true not false for leftBackSpark.follow since you dont want the individual motor moving in opposite directions (causes gear grinding and other bad stuff). Fixed it with the latest commit.

**Comment by aditya917** [comment]
The boolean is for inverting. But other than that, is the neo subsystem done?

**Comment by ayushdewan** [comment]
According to the docs, setting it to false means it sends the opposite voltage signal to leftBackSpark when you actually want the **same** voltage signal.

**Comment by ayushdewan** [comment]
Other than that, the NEO subsystem looks great.
