### ISSUE TITLE
NEO Drivetrain Extensions

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#7]
For the NEODrivetrain class that was added, implement some functions that read values from the NEO encoders to find out wheel position and velocity. It would be helpful to call them getLeftPosition(), getRightPosition(), getLeftVelocity(), and getRightVelocity(). This way its easier to test the encoder quality.

**Comment by avyayv** [comment]
This has been updated in the iterative branch, @aditya917 please fix on the master (command-based) branch.

Once we have the electronics for the neos set up, we will test out and put all this info on smartdashboard.

**Comment by aditya917** [comment]
I added the position and velocity of the encoders

**Comment by ayushdewan** [comment]
Make them functions of the NEODrivetrain class. See the iterative branch for how it was done.

**Comment by ayushdewan** [comment]
Also the slave's encoder values are going to be the same as their master's encoder values. Only use the masters for encoder readings.

**Comment by avyayv** [comment]
Fixed these issues on master
