### ISSUE TITLE
Update CTRE Library

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#8]
https://phoenix-documentation.readthedocs.io/en/latest/blog/blog-kickoff-2020.html

**Comment by aditya917** [comment]
I already downloaded the library and updated Phoenix Tuner.

**Comment by ayushdewan** [comment]
Update the Phoenix.json file in vendordeps as well

**Comment by ayushdewan** [comment]
I did it by going to "Manage vendor libraries" and selecting check for updates online

**Comment by aditya917** [comment]
I updated the json file.
