### ISSUE TITLE
NEO CAN id constant

### ISSUE THREAD

**Issue by avyayv** [Team2489/Generic-Robot-Code#9]
@aditya917  could you remove your CAN constants that are specific for the NEO and switch them to be the same as the normal talon SRX drive train constants?

**Comment by aditya917** [comment]
What do you mean?

**Comment by avyayv** [comment]
Look at the iterative branch. The CAN IDs are different for the NEO drive
train in your code, but I want them to be the same.

**Comment by avyayv** [comment]
Fixed
